-- Generated baseline migration. Prisma owns subsequent schema evolution.
CREATE TABLE "Candidate" ("id" TEXT PRIMARY KEY, "profileVersion" TEXT NOT NULL UNIQUE, "profile" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Resume" ("id" TEXT PRIMARY KEY, "candidateId" TEXT NOT NULL REFERENCES "Candidate"("id") ON DELETE CASCADE, "sourcePath" TEXT NOT NULL, "contentHash" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ResumeVersion" ("id" TEXT PRIMARY KEY, "resumeId" TEXT NOT NULL REFERENCES "Resume"("id") ON DELETE CASCADE, "jobId" TEXT, "content" TEXT NOT NULL, "claims" JSONB NOT NULL, "promptVersion" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Job" ("id" TEXT PRIMARY KEY, "source" TEXT NOT NULL, "sourceJobId" TEXT, "company" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "location" TEXT, "employmentType" TEXT, "salary" TEXT, "url" TEXT NOT NULL, "canonicalUrl" TEXT NOT NULL UNIQUE, "contentHash" TEXT NOT NULL, "postedAt" TIMESTAMP(3), "discoveredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "status" TEXT NOT NULL DEFAULT 'DISCOVERED');
CREATE UNIQUE INDEX "Job_source_sourceJobId_key" ON "Job"("source", "sourceJobId");
CREATE INDEX "Job_company_title_location_idx" ON "Job"("company", "title", "location"); CREATE INDEX "Job_contentHash_idx" ON "Job"("contentHash");
CREATE TABLE "JobRequirement" ("id" TEXT PRIMARY KEY, "jobId" TEXT NOT NULL REFERENCES "Job"("id") ON DELETE CASCADE, "category" TEXT NOT NULL, "requirement" TEXT NOT NULL, "mandatory" BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE "JobMatch" ("id" TEXT PRIMARY KEY, "jobId" TEXT NOT NULL REFERENCES "Job"("id") ON DELETE CASCADE, "profileVersion" TEXT NOT NULL, "cacheKey" TEXT NOT NULL UNIQUE, "result" JSONB NOT NULL, "provider" TEXT NOT NULL, "model" TEXT NOT NULL, "promptVersion" TEXT NOT NULL, "tokenUsage" JSONB, "estimatedCost" DECIMAL(12,6), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Application" ("id" TEXT PRIMARY KEY, "jobId" TEXT NOT NULL UNIQUE REFERENCES "Job"("id") ON DELETE CASCADE, "resumeVersionId" TEXT REFERENCES "ResumeVersion"("id"), "status" TEXT NOT NULL DEFAULT 'DISCOVERED', "browserStatus" TEXT, "submissionUrl" TEXT, "submittedAt" TIMESTAMP(3), "error" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ApplicationAnswer" ("id" TEXT PRIMARY KEY, "applicationId" TEXT NOT NULL REFERENCES "Application"("id") ON DELETE CASCADE, "question" TEXT NOT NULL, "answer" TEXT, "classification" TEXT NOT NULL, "status" TEXT NOT NULL, "confidence" TEXT NOT NULL, "sourceRefs" JSONB NOT NULL);
CREATE TABLE "ApplicationEvent" ("id" TEXT PRIMARY KEY, "applicationId" TEXT NOT NULL REFERENCES "Application"("id") ON DELETE CASCADE, "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "eventType" TEXT NOT NULL, "status" TEXT NOT NULL, "message" TEXT NOT NULL, "metadata" JSONB); CREATE INDEX "ApplicationEvent_applicationId_timestamp_idx" ON "ApplicationEvent"("applicationId", "timestamp");
CREATE TABLE "JobSource" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL UNIQUE, "type" TEXT NOT NULL, "config" JSONB NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "AutomationRun" ("id" TEXT PRIMARY KEY, "type" TEXT NOT NULL, "idempotencyKey" TEXT NOT NULL UNIQUE, "status" TEXT NOT NULL, "stats" JSONB NOT NULL DEFAULT '{}', "estimatedCost" DECIMAL(12,6), "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMP(3));
CREATE TABLE "UserApproval" ("id" TEXT PRIMARY KEY, "applicationId" TEXT NOT NULL REFERENCES "Application"("id") ON DELETE CASCADE, "approved" BOOLEAN NOT NULL, "actor" TEXT NOT NULL, "note" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
